/// Flutter icons MXCIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MXCIcons
///      fonts:
///       - asset: fonts/MXCIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class MXCIcons {
  MXCIcons._();

  static const _kFontFam = 'MXCIcons';
  static const String? _kFontPkg = null;

  static const IconData show = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData increase = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_link = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrease = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger_menu = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_up = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_down = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chain_configuration = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conversion = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropdown_down = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_dir = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
