name: web3_provider
description: The bridge communicate between in-app webview and mobile-app by standard EIP-1193.
version: 1.1.3
homepage: https://github.com/PositionExchange/flutter-web3-provider

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  decimal: ^2.3.0
  flutter_inappwebview: ^6.1.5
  mxc_logic:
    path: ../shared/logic

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Graphql 5.1.3 requires this version so we override this
  # for phoenix_socket to use lower version of ws  
  web_socket_channel: ^2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - packages/web3_provider/assets/posi.min.js
